// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo0OtaDJ_BpQW1wCA2osXeywmJrbdF-f0',
    appId: '1:358267145718:android:ca5cc95976f0c290d28bd7',
    messagingSenderId: '358267145718',
    projectId: 'martify-a40e0',
    storageBucket: 'martify-a40e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0GCEFNkpDft-y8daD_Dn5uB25U2yuAO8',
    appId: '1:358267145718:ios:a30b4e2226e15d54d28bd7',
    messagingSenderId: '358267145718',
    projectId: 'martify-a40e0',
    storageBucket: 'martify-a40e0.appspot.com',
    androidClientId: '358267145718-jg2j5mfvu4bss23il5ab6bifc7mbkr3c.apps.googleusercontent.com',
    iosClientId: '358267145718-o9so7763ooee9qp9acgbvv3no1664m59.apps.googleusercontent.com',
    iosBundleId: 'com.example.martify',
  );

}